//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbertSession2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Events()
        {
            this.RequestedItems = new HashSet<RequestedItems>();
        }
    
        public int event_id { get; set; }
        public int user_id { get; set; }
        public int location_id { get; set; }
        public string name { get; set; }
        public System.DateTime start { get; set; }
        public System.DateTime end { get; set; }
    
        public virtual Locations Locations { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestedItems> RequestedItems { get; set; }
    }
}
