//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbertSession2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        public int reservationId { get; set; }
        public Nullable<int> requestId { get; set; }
        public Nullable<int> offerId { get; set; }
        public Nullable<int> reservedByUserId { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
    
        public virtual Offers Offers { get; set; }
        public virtual RequestedItems RequestedItems { get; set; }
        public virtual Users Users { get; set; }
    }
}
