//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbertSessionFive
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direction
    {
        public Direction()
        {
            this.Gaps = new HashSet<Gap>();
        }
    
        public int direction_id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Gap> Gaps { get; set; }
    }
}
