//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbertSessionFive
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Events = new HashSet<Event>();
            this.Gaps = new HashSet<Gap>();
            this.UnavailableSeats = new HashSet<UnavailableSeat>();
        }
    
        public int location_id { get; set; }
        public string name { get; set; }
        public int rows { get; set; }
        public int seats_per_row { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<Gap> Gaps { get; set; }
        public virtual ICollection<UnavailableSeat> UnavailableSeats { get; set; }
    }
}
