//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbertSessionFive
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class albertFiveEntities : DbContext
    {
        public albertFiveEntities()
            : base("name=albertFiveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Direction> Directions { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<Gap> Gaps { get; set; }
        public DbSet<Location> Locations { get; set; }
        public DbSet<UnavailableSeat> UnavailableSeats { get; set; }
    }
}
