//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbertSessionFive
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnavailableSeat
    {
        public int unavailable_seat_id { get; set; }
        public int location_id { get; set; }
        public int row { get; set; }
        public int seat { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
