id=location-869d61a3-95a5-44e7-a4dc-9f1b84034d
name=Lakeview Pavilion
location=Müritz National Park
max_visitors=70
description=Perched on the shores of a tranquil lake in Müritz National Park, this pavilion offers stunning views and a peaceful atmosphere for small events. Guests can enjoy the beauty of nature while celebrating special occasions.