id=location-527450d8-fb49-4661-9642-ad5597ee40
name=Riverside Cabin
location=Peene Valley
max_visitors=30
description=Located along the banks of the Peene River, this cozy cabin provides an intimate setting for small events. Guests can enjoy fishing, kayaking, and serene views of the river.