id=location-d5e9aff4-92e4-4453-93e1-f779e599ba
name=Enchanted Gardens
location=Schwerin
max_visitors=100
description=A magical garden venue perfect for intimate gatherings and outdoor events. Surrounded by lush greenery and enchanting flowers, it provides a serene atmosphere for your event.