id=location-29086e38-6188-46d8-aa35-1607433907
name=Forest Retreat Lodge
location=Müritz National Park
max_visitors=50
description=Nestled in the heart of Müritz National Park, this rustic lodge offers a tranquil escape for small events. Surrounded by pristine forests and wildlife, it's ideal for nature-themed gatherings.