id=location-aae5c9ff-e6a7-45cc-a498-8f7a5f88a1
name=Art Gallery Loft
location=Rostock
max_visitors=80
description=Host your event in this trendy loft space located in the vibrant city of Rostock. Adorned with contemporary artwork, it provides a chic setting for art exhibitions, receptions, and more.