id=location-c5bb6f93-d29c-4226-982f-8dcccc3221
name=Rural Farmhouse
location=Feldberger Seenlandschaft
max_visitors=40
description=Experience the charm of rural Mecklenburg-Vorpommern at this quaint farmhouse nestled in the Feldberger Seenlandschaft. Surrounded by meadows and forests, it provides a cozy setting for intimate gatherings and country-themed events.