id=location-71f36516-a431-4ef0-bc70-005fc96816
name=Lakeside Lodge
location=Tollensesee
max_visitors=60
description=Enjoy panoramic views of Tollensesee from this charming lakeside lodge near Neubrandenburg. With its cozy atmosphere and scenic surroundings, it offers a relaxing setting for small events, such as family reunions and corporate retreats.