id=location-819a9b12-d9aa-4993-8f35-93ba28880d52
name=Town Hall Courtyard
location=Neustrelitz
max_visitors=120
description=Located in the heart of Neustrelitz, the town hall courtyard offers a historic backdrop for small events. With its elegant architecture and central location, it's an ideal venue for cultural festivities and community gatherings.
