id=location-8800a6ed-b39f-449f-8d2c-90a9819a40b6
name=Castle Courtyard
location=Schwerin
max_visitors=150
description=Host your event in the historic courtyard of Schwerin Castle, surrounded by centuries-old architecture and a sense of grandeur. Perfect for cultural gatherings and elegant affairs.
