id=location-45a8c8b6-d159-4b95-b671-6d99754b8207
name=Forest Cabin Retreat
location=Neubrandenburg Heath
max_visitors=50
description=Escape to the tranquility of Neubrandenburg Heath and host your event at this secluded forest cabin retreat. Surrounded by towering trees and wildlife, it's the perfect spot for outdoor adventures and rustic celebrations.
