id=location-c737822a-3610-4b76-ba09-66581c16da06
name=Lakeside Pavilion
location=Schwerin Lake
max_visitors=50
description=Enjoy panoramic views of Schwerin Lake from this charming lakeside pavilion. Surrounded by nature, it offers a peaceful setting for small events, such as weddings and family gatherings.
