id=location-f317dfc4-174c-4ad3-aecc-9540776e0ce6
name=Coastal Lighthouse
location=Darßer Ort
max_visitors=40
description=Perched atop a picturesque cliff, this historic lighthouse offers a unique venue for small events. Guests can marvel at breathtaking coastal views and explore the surrounding nature reserve.
