id=location-60537ef3-841b-4cd4-876a-2e981819b68d
name=Riverside Cabin
location=Peene Valley
max_visitors=30
description=Located along the banks of the Peene River, this cozy cabin provides an intimate setting for small events. Guests can enjoy fishing, kayaking, and serene views of the river.
