id=location-c12e0315-c3f5-448a-b8ae-da4c58b4e24d
name=Lakeside Pavilion
location=Schwerin Lake
max_visitors=50
description=Enjoy panoramic views of Schwerin Lake from this charming lakeside pavilion. Surrounded by nature, it offers a peaceful setting for small events, such as weddings and family gatherings.
