id=location-31e4875e-8a26-412b-bc71-d4d6f7a159db
name=Castle Courtyard
location=Schwerin
max_visitors=150
description=Host your event in the historic courtyard of Schwerin Castle, surrounded by centuries-old architecture and a sense of grandeur. Perfect for cultural gatherings and elegant affairs.
