id=location-61134c10-2069-43d3-986e-a08c2122ba93
name=Seaside Pavilion
location=Warnemünde
max_visitors=80
description=Overlooking the Baltic Sea, this charming seaside pavilion offers a picturesque setting for small events. Guests can enjoy stunning ocean views and fresh sea breeze.
