id=location-8784b4a9-09b7-47c3-90d1-3ba0c4c47991
name=Forest Retreat Lodge
location=Müritz National Park
max_visitors=50
description=Nestled in the heart of Müritz National Park, this rustic lodge offers a tranquil escape for small events. Surrounded by pristine forests and wildlife, it's ideal for nature-themed gatherings.
