id=location-45425d69-caa2-47a4-8efd-a1fd7b1f42c8
name=Enchanted Gardens
location=Schwerin
max_visitors=100
description=A magical garden venue perfect for intimate gatherings and outdoor events. Surrounded by lush greenery and enchanting flowers, it provides a serene atmosphere for your event.
