id=location-438353b1-9664-4d0e-b34f-8c419bd017ca
name=Historic Manor House
location=Usedom Island
max_visitors=120
description=Step back in time and host your event in this beautifully preserved manor house on Usedom Island. With elegant interiors and sprawling gardens, it exudes old-world charm and sophistication.
