id=location-8e5c9cb8-c991-4dec-bab3-3a0f8a5a87a8
name=Lakeside Lodge
location=Tollensesee
max_visitors=60
description=Enjoy panoramic views of Tollensesee from this charming lakeside lodge near Neubrandenburg. With its cozy atmosphere and scenic surroundings, it offers a relaxing setting for small events, such as family reunions and corporate retreats.
