id=location-7782192e-ca12-4ed3-9934-6f2c59ee07f0
name=Seaside Pavilion
location=Warnemünde
max_visitors=80
description=Overlooking the Baltic Sea, this charming seaside pavilion offers a picturesque setting for small events. Guests can enjoy stunning ocean views and fresh sea breeze.
