id=location-4949a467-f1ea-4ee7-ad73-c330b60ea5b4
name=Historic Manor House
location=Usedom Island
max_visitors=120
description=Step back in time and host your event in this beautifully preserved manor house on Usedom Island. With elegant interiors and sprawling gardens, it exudes old-world charm and sophistication.
