id=location-c52624ba-330e-4475-8b46-4f67d75ed80f
name=Art Gallery Loft
location=Rostock
max_visitors=80
description=Host your event in this trendy loft space located in the vibrant city of Rostock. Adorned with contemporary artwork, it provides a chic setting for art exhibitions, receptions, and more.
