id=location-2e7fb52d-b22d-4b2e-8ae4-896941aa23c1
name=Town Hall Courtyard
location=Neustrelitz
max_visitors=120
description=Located in the heart of Neustrelitz, the town hall courtyard offers a historic backdrop for small events. With its elegant architecture and central location, it's an ideal venue for cultural festivities and community gatherings.
