id=location-641b8f49-3cf7-4da5-8c96-f38d50e114af
name=Lakeview Pavilion
location=Müritz National Park
max_visitors=70
description=Perched on the shores of a tranquil lake in Müritz National Park, this pavilion offers stunning views and a peaceful atmosphere for small events. Guests can enjoy the beauty of nature while celebrating special occasions.
