id=location-91555950-e91e-48b2-9b68-5a08f33d6c43
name=Coastal Lighthouse
location=Darßer Ort
max_visitors=40
description=Perched atop a picturesque cliff, this historic lighthouse offers a unique venue for small events. Guests can marvel at breathtaking coastal views and explore the surrounding nature reserve.
