id=location-3e204e00-5610-4bff-a5fb-f72237d1c153
name=Vineyard Terrace
location=Mecklenburg Lake District
max_visitors=60
description=Set amidst rolling hills and vineyards, this charming terrace offers a scenic backdrop for small events. Guests can savor local wines while enjoying panoramic views of the countryside.
