//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbertSession1
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public string name { get; set; }
        public string location { get; set; }
        public System.DateTime start { get; set; }
        public System.DateTime end { get; set; }
        public byte price_in_euro { get; set; }
        public string program { get; set; }
        public string pictures { get; set; }
        public string state { get; set; }
        public string rejectionReason { get; set; }
        public string organizer { get; set; }
        public int id { get; set; }
        public Nullable<int> venueId { get; set; }
    
        public virtual venue venue { get; set; }
    }
}
