//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbertSession1
{
    using System;
    using System.Collections.Generic;
    
    public partial class moderator
    {
        public int id { get; set; }
        public string role { get; set; }
        public string email { get; set; }
        public string passwordm { get; set; }
        public string given_name { get; set; }
        public string family_name { get; set; }
        public string town { get; set; }
        public System.DateTime birthday { get; set; }
        public short postal_code { get; set; }
        public string street_number { get; set; }
        public string phone { get; set; }
    }
}
