//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbertSession1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class albertEntities1 : DbContext
    {
        public albertEntities1()
            : base("name=albertEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<@event> @event { get; set; }
        public DbSet<moderator> moderator { get; set; }
        public DbSet<organizer> organizer { get; set; }
        public DbSet<users> users { get; set; }
        public DbSet<venue> venue { get; set; }
    }
}
