//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbertSession1
{
    using System;
    using System.Collections.Generic;
    
    public partial class organizer
    {
        public string email { get; set; }
        public string passwordo { get; set; }
        public string pre_name { get; set; }
        public string family_name { get; set; }
        public string Postal_code_and_town { get; set; }
        public System.DateTime birthday { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string hobby { get; set; }
        public int id { get; set; }
    }
}
