//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbertSession1
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int id { get; set; }
        public string email { get; set; }
        public string passworduser { get; set; }
        public Nullable<short> is_moderator { get; set; }
        public Nullable<int> FailedAttempts { get; set; }
        public Nullable<System.DateTime> LastFailedLogin { get; set; }
        public Nullable<bool> IsBanned { get; set; }
    }
}
