//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbertSession1
{
    using System;
    using System.Collections.Generic;
    
    public partial class venue
    {
        public venue()
        {
            this.@event = new HashSet<@event>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string location { get; set; }
    
        public virtual ICollection<@event> @event { get; set; }
    }
}
