//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AESessionThreeWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public string Id { get; set; }
        public string UserId { get; set; }
        public string TicketId { get; set; }
        public System.DateTime BoughtAt { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Ticket Ticket { get; set; }
        public virtual User User { get; set; }
    }
}
