//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AESessionThreeWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error
    {
        public int id { get; set; }
        public Nullable<int> errorLine { get; set; }
        public string errorText { get; set; }
        public string errorMessage { get; set; }
    }
}
