//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AESessionThreeWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public string Id { get; set; }
        public string OrganizerId { get; set; }
        public string LocationId { get; set; }
        public string EventGroupId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime StartsAt { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
        public Nullable<decimal> BaseDemand { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Hosts { get; set; }
    
        public virtual EventGroup EventGroup { get; set; }
        public virtual Location Location { get; set; }
        public virtual Organizer Organizer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
