//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AESessionThreeWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketTier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TicketTier()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public string Id { get; set; }
        public string EventGroupId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
    
        public virtual EventGroup EventGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
